### ISSUE TITLE
[Resource] Split Resource into small protocols

### ISSUE THREAD

**Issue by portellaa** [Mindera/Alicerce#111]
# Problem

Currently the Resource protocol contains all the closures for parse, serialise and error. Probably most of the times those closures aren't used by the implementations and we have to implement it with fatalError.

# Solution

Split this in multiple protocols. Any other idea?

This was previously discussed with @p4checo. This is just a reminder so we can discuss this later.

Bringing @danieladias into discussion.

**Comment by p4checo** [comment]
We should definitely tackle this! ⛏ 

Breaking them into smaller (compassable) protocols seems to be the way to go. We should also probably decouple them more from the network stack(s), and make them more self contained? We need to do some brainstorming 😛 

To make things more interesting, we now also have another edge case like a Resource that doesn't receive payload (and thus doesn't require parsing) 😆

**Comment by renatorodrigues** [comment]
I will work on this and present a proposal soon.

**Comment by portellaa** [comment]
I have this kind of done, already. although, feel free to do it if you want 🙂. 
i will push the branch as soon as possible, so you can take a look, if you want 😀
