### ISSUE TITLE
Networking examples

### ISSUE THREAD

**Issue by dev4jam** [Mindera/Alicerce#118]
Could you please give several networking examples and/or networking stack architecture if possible.

**Comment by p4checo** [comment]
hi @dev4jam 🤝 

Thanks for opening this issue! We definitely have to add some examples to our README, and also an example app and/or playgrounds.

Hopefully we'll add them soon! 🙏

**Comment by renatorodrigues** [comment]
I will write some documentation with some examples.

**Comment by renatorodrigues** [comment]
@dev4jam, #142 just got merged which adds documentation to get started with the network stack.
