### ISSUE TITLE
Could you give some example use this frame work?

### ISSUE THREAD

**Issue by dongshuju** [Mindera/Alicerce#121]
Some part is hard to understand, if there are any example project will help to use this framework

**Comment by p4checo** [comment]
Hi @dongshuju! 🤝 

Yes, we are aware that some examples are missing 😓, and we'll try to add them as soon as possible.

What parts did you find hard to understand? (so that perhaps we could focus on those first)

Cheers! 🍻

**Comment by renatorodrigues** [comment]
@dongshuju we just merged a PR with documentation for the network stack. Soon, we will also make available a playground where you can see Alicerce in action.
