### ISSUE TITLE
Create submodules / subspecs

### ISSUE THREAD

**Issue by p4checo** [Mindera/Alicerce#122]
Since framework users might only be interested in a subset of the framework's features, it makes sense to allow partial importing.

CocoaPods allows this to be done quite easily by using [Subspecs](https://guides.cocoapods.org/syntax/podspec.html#group_subspecs)

Carthage seems to have no official support for this (and it might even be [against their philosphy](https://github.com/Carthage/Carthage/issues/588#issuecomment-116137295))

Perhaps in the future it might make sense to break Alicerce into smaller µFrameworks, because this issue will tend to worsen as we add more functionalities to it 😅

**Comment by beloso** [comment]
I would like to help out with this. But I need to have a greater understanding of what subspecs would make sense. And probably the project's file structure would need to adapt to that.

**Comment by p4checo** [comment]
Great! 💪 

Agreed, we should discuss what subspecs make sense, and we will most likely have to restructure the project.

On a first analysis, I could see the following subspecs (to be used as a starting point):

- Core (Shared stuff, eg. `Resource`)
  + Core/Utils (Extensions, Observers, Utils)
- Analytics
- DeepLinking
- Logging
- PerformanceMetrics
- Stores (dependent on Network and Persistence)
  + Stores/CoreData (in the future?)
- Network
- Persistence
  + Persistence/CoreData
- UI
  + UI/BaseViews
  + UI/Utils (UIKit and QuartzCore extensions)
  + UI/ReusableView

**Comment by beloso** [comment]
Perhaps we should wait for the discussion of #111 as it seems relevant to this no?

**Comment by AlexanderNorway** [comment]
Any update on this?

**Comment by p4checo** [comment]
Hi @AlexanderNorway 🤝 

I've picked this up and will open a PR in the coming days. 

Out of curiosity, what parts of Alicerce are you using, or would be interested in?

Cheers! 🍻
