### ISSUE TITLE
Use `Result` for asynchronous calls?

### ISSUE THREAD

**Issue by p4checo** [Mindera/Alicerce#123]
When creating Alicerce we agreed that (ideally) it wouldn't have any 3rd party dependency.

Even though we love [`Result`](https://github.com/antitypical/Result) and use it on our projects, this also meant we wouldn't use on Alicerce 😢.

Because of this decision (in great part because of me 😇), we ended up using completion closures with throwing inner closures on our async code (e.g. `typealias CompletionClosure<R> = (_ inner: () throws -> R) -> Void`), which are hard to write, hard to read, and honestly quite ugly.

While the idea was for framework users to make their own wrappers around these API's using extensions (and we currently do that with `ReactiveSwift`'s `SignalProducer`, for example), we still have to design and maintain them using this approach, for consistency.

That being said, I am opening up this issue to discuss some possibilities regarding this situation:

1. import [`Result`](https://github.com/antitypical/Result)
2. create our own `Result`
3. keep things unchanged

**Comment by beloso** [comment]
In my opinion we should import Result.

To create another Result, as easy as it would be, would be to double the work. Also a lot of effort was already put into testing Result, we can be confident that it should be working as it should.
