### ISSUE TITLE
Revise `Equatable` and `Hashable` conformances

### ISSUE THREAD

**Issue by p4checo** [Mindera/Alicerce#138]
Since Swift 4.1 that [`Equatable` and `Hashable` conformances can be auto synthesized](https://github.com/apple/swift-evolution/blob/master/proposals/0185-synthesize-equatable-hashable.md)

We currently have some case were we can most likely take advantage of this 💪

**Comment by IvoPintodaSilva** [comment]
https://github.com/Mindera/Alicerce/pull/141 Merged
