### ISSUE TITLE
Network Documentation

### ISSUE THREAD

**Issue by dehlen** [Mindera/Alicerce#163]
Hey, it looks like the Network documentation is based on an old version of this framework. To me it looks like that the example `RESTResource<T: Codable>` class has to implement the `RetryableResource` protocol. I added conformance to the protocol and the following implementation which I hope is the way to go.

` var retryErrors: [Swift.Error] = []
    var totalRetriedDelay: ResourceRetry.Delay = 0
    var retryPolicies: [ResourceRetry.Policy<Data, URLRequest, URLResponse>] = []

    typealias Request = URLRequest
    typealias Response = URLResponse`
If you would confirm this I would love to make PR in order to correct the documentation.

However I am currently searching for a way to authenticate my network stack using OAuth2 (GitHub API). I think this should be fairly easy be possible by using the `NetworkAuthenticator` and `AuthenticationChallengeHandler`, but I would love some guidance since I am not quite sure at the moment on how to implement this. Could you help me out here with some information on how to add that to the network stack ?

**Comment by p4checo** [comment]
hi @dehlen 👋 

Sorry for the late reply. Yes, we forgot to update our Playground with the latest changes. 😓
The snippet you mention should do the job, so feel free to open a PR!

As for your second question, I think you might be able to achieve that via a `NetworkAuthenticator` implementation. The `AuthenticationChallengeHandler` is designed to work with `URLAuthenticationChallenge` API's, which are used at a lower level of authentication (e.g. establishing an encrypted TLS session) and shouldn't be what you're looking for.

So in essence you could create an `OAuth2NetworkAuthenticator: NetworkAuthenticator` implementing the OAuth2 protocol logic, and then inject it on your `URLNetworkStack`. That way, whenever the network stack performs a fetch and requests an authentication (via `authenticate`), your authenticator would enrich the `URLRequest` with the necessary credentials, or trigger the mechanisms to fetch/refresh them and then enrich the request when possible.

If you also make your authenticator conform to `RetryableNetworkAuthenticator`, you will then have to supply a retry policy (which you set on your Resources) that will allow you to react to authentication errors (e.g. 403's), trigger internal token refresh mechanisms and obviously determine whether a request should be retried or not from an authentication perspective.

Hope this made sense! Cheers! 🍻
